name = "limitless-mcp-remote"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "LimitlessMCP" }
]

[[migrations]]
tag = "v1"
new_classes = ["LimitlessMCP"]

[[kv_namespaces]]
binding = "OAUTH_STORAGE"
id = "5896b24addba42c99c0e099490ef5a4e"
preview_id = "oauth_storage_preview"